import { Geist, Geist_Mono, Patrick_Hand } from "next/font/google";
import Link from "next/link";
import { LuArrowRight } from "react-icons/lu";
import "./rootlayout.css";
import ThemeToggle from "./themetoggle/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-patrick-hand",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body style={{ backgroundColor: "var(--background-color)" }}>
        <div style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: 'center' }}>
          <nav className="nav-container">
            <div className="nav-inner">
              <Link href="/hero" className="logo-link">
                <div className="logo-image"></div>
              </Link>

              <div className="heroBtndiv">
                <Link href="/documentation" passHref legacyBehavior>
                  <a className="docs-link">Read docs</a>
                </Link>

                <Link href="/scannerboard" passHref legacyBehavior>
                  <a className="scan-link">Scan repo</a>
                </Link>
              </div>

            </div>
            <ThemeToggle/>

          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
